import reducer from "./reducers";

test("should return the empty initial state", () => {
  expect(reducer(undefined, {})).toEqual({
    showSearchBar: false,
    showTicketPurchaseForm: false,
    showFilter: false,
    genres: [
      {
        name: "Akcja",
        filter: false,
      },
      {
        name: "Animacja",
        filter: false,
      },
      {
        name: "Dramat",
        filter: false,
      },
      {
        name: "Horror",
        filter: false,
      },
      {
        name: "Komedia",
        filter: false,
      },
      {
        name: "Rodzinny",
        filter: false,
      },
      {
        name: "Romans",
        filter: false,
      },
      {
        name: "Thriller",
        filter: false,
      },
    ],
    age: [
      {
        category: "Familijny",
        filter: false,
      },
      {
        category: "13+",
        filter: false,
      },
      {
        category: "17+",
        filter: false,
      },
    ],
    films: [],
    calendar: [],
    todayFilms: {},
    tomorrowFilms: {},
  });
});

test("should hide SearchBar if it is visible", () => {
  expect(
    reducer(
      { showSearchBar: true },
      {
        type: "TOGGLE_SEARCHBAR",
      }
    )
  ).toEqual({
    showSearchBar: false,
  });
});

test("should show SearchBar if it is hidden", () => {
  expect(
    reducer(
      { showSearchBar: false },
      {
        type: "TOGGLE_SEARCHBAR",
      }
    )
  ).toEqual({
    showSearchBar: true,
  });
});

test("should hide TicketPurchaseForm if it is visible", () => {
  expect(
    reducer(
      { showTicketPurchaseForm: true },
      {
        type: "TOGGLE_TICKETPURCHASEFORM",
      }
    )
  ).toEqual({
    showTicketPurchaseForm: false,
  });
});

test("should show TicketPurchaseForm if it is hidden", () => {
  expect(
    reducer(
      { showTicketPurchaseForm: false },
      {
        type: "TOGGLE_TICKETPURCHASEFORM",
      }
    )
  ).toEqual({
    showTicketPurchaseForm: true,
  });
});

test("should hide Filter if it is shown", () => {
  expect(reducer({ showFilter: true }, { type: "TOGGLE_FILTER" })).toEqual({
    showFilter: false,
  });
});

test("should show Filter if it is hidden", () => {
  expect(reducer({ showFilter: false }, { type: "TOGGLE_FILTER" })).toEqual({
    showFilter: true,
  });
});

test("should toggle genre.filter to true if it is false", () => {
  const mockGenre = "Komedia";
  expect(
    reducer(
      {
        genres: [
          { name: mockGenre, filter: false },
          { name: "Dramat", filter: false },
        ],
      },
      { type: "TOGGLE_GENRE_FILTER", genre: mockGenre }
    )
  ).toEqual({
    genres: [
      { name: mockGenre, filter: true },
      { name: "Dramat", filter: false },
    ],
  });
});

test("should toggle genre.filter to false if it is true", () => {
  const mockGenre = "Romans";
  expect(
    reducer(
      {
        genres: [
          { name: mockGenre, filter: true },
          { name: "Dramat", filter: true },
        ],
      },
      { type: "TOGGLE_GENRE_FILTER", genre: mockGenre }
    )
  ).toEqual({
    genres: [
      { name: mockGenre, filter: false },
      { name: "Dramat", filter: true },
    ],
  });
});

test("should toggle age.filter to true if it is false", () => {
  const mockAge = "12+";
  expect(
    reducer(
      {
        age: [
          { category: mockAge, filter: false },
          { category: "15+", filter: false },
        ],
      },
      { type: "TOGGLE_AGE_FILTER", age: mockAge }
    )
  ).toEqual({
    age: [
      { category: mockAge, filter: true },
      { category: "15+", filter: false },
    ],
  });
});

test("should toggle age.filter to false if it is true", () => {
  const mockAge = "15+";
  expect(
    reducer(
      {
        age: [
          { category: mockAge, filter: true },
          { category: "18+", filter: true },
        ],
      },
      { type: "TOGGLE_AGE_FILTER", age: mockAge }
    )
  ).toEqual({
    age: [
      { category: mockAge, filter: false },
      { category: "18+", filter: true },
    ],
  });
});

test("should fetch movies from the DB", () => {
  expect(
    reducer(
      {
        films: [],
      },
      { type: "GET_MOVIES" }
    )
  ).toEqual({
    films: [
      {
        id: 1,
        title: "The Green Knight",
        year: "2020",
        rated: "N/A",
        release: "2020.05.29",
        duration: "125 min",
        genre: "Drama, Horror",
        director: "David Lowery",
        writer: "David Lowery",
        actors: "Dev Patel, Alicia Vikander, Joel Edgerton, Sarita Choudhury",
        plot:
          "A fantasy re-telling of the medieval story of Sir Gawain and the Green Knight.",
        country: "USA, Ireland",
        poster:
          "https://m.media-amazon.com/images/M/MV5BNWE1ZGE5Y2QtYWE4Yi00YjM0LThhNWYtMWM1OGJjNDU3YzMyXkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_SX300.jpg",
      },
      {
        id: 2,
        title: "Tenet",
        year: "2020",
        rated: "N/A",
        release: "2020.07.17",
        duration: "N/A",
        genre: "Action, Drama, Thriller",
        director: "Christopher Nolan",
        writer: "Christopher Nolan",
        actors:
          "Elizabeth Debicki, Robert Pattinson, Aaron Taylor-Johnson, Kenneth Branagh",
        plot:
          "An action epic revolving around international espionage, time travel, and evolution. Possibly about a man trying to prevent World War 3 through time travel and rebirth.",
        country: "USA, UK",
        poster:
          "https://m.media-amazon.com/images/M/MV5BNmMwYzFlNTEtYTc0NC00NGY4LTgzNzItZGFiYTViY2QzNzU1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
      },
      {
        id: 3,
        title: "Mulan",
        year: "2020",
        rated: "PG-13",
        release: "2020.07.24",
        duration: "115 min",
        genre: "Action, Drama, Family",
        director: "Niki Caro",
        writer: "Rick Jaffa, Amanda Silver, Elizabeth Martin, Lauren Hynek",
        actors: "Yifei Liu, Donnie Yen, Li Gong, Jet Li",
        plot:
          "A young Chinese maiden disguises herself as a male warrior in order to save her father. A live-action feature film based on Disney's 'Mulan.'",
        country: "USA",
        poster:
          "https://m.media-amazon.com/images/M/MV5BMjFlZjZkMTYtODM2Zi00OTM4LWIwYTktOTFjMmQzZDEzZDc4XkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_SX300.jpg",
      },
      {
        id: 4,
        title: "The SpongeBob Movie: Sponge on the Run",
        year: "2020",
        rated: "N/A",
        release: "2020.08.07",
        duration: "N/A",
        genre: "Animation, Comedy, Family",
        director: "Tim Hill",
        writer: "Tim Hill",
        actors: "Keanu Reeves, Clancy Brown, Awkwafina, Tom Kenny",
        plot:
          "After SpongeBob's beloved pet snail Gary is snail-napped, he and Patrick embark on an epic adventure to The Lost City of Atlantic City to bring Gary home.",
        country: "South Korea, USA",
        poster:
          "https://m.media-amazon.com/images/M/MV5BODIwMmQxNDktOWZjZC00NWI4LTg1NjktMGViOTE4ZTA4ZGY5XkEyXkFqcGdeQXVyNjg5MjU3NjE@._V1_SX300.jpg",
      },
      {
        id: 5,
        title: "A Quiet Place Part II",
        year: "2020",
        rated: "PG-13",
        release: "2020.09.04",
        duration: "97 min",
        genre: "Drama, Thriller",
        director: "John Krasinski",
        writer: "Scott Beck, John Krasinski, Bryan Woods",
        actors: "Emily Blunt, Millicent Simmonds, Cillian Murphy, Noah Jupe",
        plot:
          "Following the events at home, the Abbott family now face the terrors of the outside world. Forced to venture into the unknown, they realize the creatures that hunt by sound are not the only threats lurking beyond the sand path.",
        country: "USA",
        poster:
          "https://m.media-amazon.com/images/M/MV5BMmE3OGY2NzMtMGJmOS00NGViLWI4NjYtMjhlNTMxZjA5MDExXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg",
      },
      {
        id: 6,
        title: "Candyman",
        year: "2020",
        rated: "N/A",
        release: "2020.09.25",
        duration: "N/A",
        genre: "Horror, Thriller",
        director: "Nia DaCosta",
        writer: "Jordan Peele, Win Rosenfeld, Nia DaCosta",
        actors:
          "Yahya Abdul-Mateen II, Teyonah Parris, Nathan Stewart-Jarrett, Colman Domingo",
        plot:
          "A \"spiritual sequel\" to the 1992 horror film 'Candyman' that returns to the now-gentrified Chicago neighborhood where the legend began.",
        country: "Canada, USA",
        poster:
          "https://m.media-amazon.com/images/M/MV5BM2RiMzdmZjYtY2VhZS00YzQ4LWIzNjItYWY5ZTFiNTI0ZGU3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
      },
      {
        id: 7,
        title: "Black Widow",
        year: "2020",
        rated: "Unrated",
        release: "2020.11.06",
        duration: "N/A",
        genre: "Action",
        director: "Cate Shortland",
        writer: "Jac Schaeffer, Ned Benson, Eric Pearson",
        actors:
          "Florence Pugh, Robert Downey Jr., Scarlett Johansson, David Harbour",
        plot:
          "A film about Natasha Romanoff in her quests between the films Civil War and Infinity War.",
        country: "USA",
        poster:
          "https://m.media-amazon.com/images/M/MV5BZGRlNTY3NGYtM2YzZS00N2YyLTg0ZDYtNmY2ZDg2NDM3N2JlXkEyXkFqcGdeQXVyNTI4MzE4MDU@._V1_SX300.jpg",
      },
      {
        id: 8,
        title: "No Time to Die",
        year: "2020",
        rated: "PG-13",
        release: "2020.11.25",
        duration: "163 min",
        genre: "Action, Thriller",
        director: "Cary Joji Fukunaga",
        writer:
          "Neal Purvis, Robert Wade, Cary Joji Fukunaga, Phoebe Waller-Bridge",
        actors: "Ana de Armas, Daniel Craig, Ralph Fiennes, Léa Seydoux",
        plot:
          "James Bond has left active service. His peace is short-lived when Felix Leiter, an old friend from the CIA, turns up asking for help, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.",
        country: "UK, USA",
        poster:
          "https://m.media-amazon.com/images/M/MV5BNGEwMDU2ZDQtZmE5Zi00YjFiLWIwYWItOGMyMzY5MzljOWU3XkEyXkFqcGdeQXVyODk2NDQ3MTA@._V1_SX300.jpg",
      },
      {
        id: 9,
        title: "Soul",
        year: "2020",
        rated: "N/A",
        release: "2020.11.20",
        duration: "N/A",
        genre: "Animation, Comedy, Family",
        director: "Pete Docter, Kemp Powers(co-director)",
        writer: "Pete Docter, Mike Jones, Kemp Powers",
        actors: "Jamie Foxx, Tina Fey, Quest Love, Phylicia Rashad",
        plot:
          "A musician who has lost his passion for music is transported out of his body and must find his way back with the help of an infant soul learning about herself.",
        country: "USA",
        poster:
          "https://m.media-amazon.com/images/M/MV5BN2YxY2M5N2YtZmJhNS00YTE1LWE5OTQtMTYyYzkyMzIzOTE1XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
      },
      {
        id: 10,
        title: "Free Guy",
        year: "2020",
        rated: "N/A",
        release: "2020.12.11",
        duration: "N/A",
        genre: "Action, Comedy",
        director: "Shawn Levy",
        writer: "Matt Lieberman, Matt Lieberman, Zak Penn",
        actors: "Jodie Comer, Taika Waititi, Ryan Reynolds, Joe Keery",
        plot:
          "A bank teller discovers that he's actually an NPC inside a brutal, open world video game.",
        country: "USA",
        poster:
          "https://m.media-amazon.com/images/M/MV5BNzE5YzVjZmEtNGYwZi00YjljLWExMzYtZjlkYTk4NDc0MmI5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
      },
      {
        id: 11,
        title: "Top Gun: Maverick",
        year: "2020",
        rated: "N/A",
        release: "2020.12.23",
        duration: "N/A",
        genre: "Action, Drama",
        director: "Joseph Kosinski",
        writer: "Ehren Kruger, Eric Warren Singer, Christopher McQuarrie",
        actors: "Tom Cruise, Jennifer Connelly, Val Kilmer, Ed Harris",
        plot:
          "After more than thirty years of service as one of the Navy's top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.",
        country: "USA, Hong Kong",
        poster:
          "https://m.media-amazon.com/images/M/MV5BNTEyYTA5YWYtYmIxYS00NWRlLWExNjMtNjliZmVlZDgxNTBlXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
      },
      {
        id: 12,
        title: "Ghostbusters: Afterlife",
        year: "2021",
        rated: "N/A",
        release: "2021.03.05",
        duration: "N/A",
        genre: "Comedy, Action",
        director: "Jason Reitman",
        writer: "Gil Kenan, Jason Reitman",
        actors: "Paul Rudd, Mckenna Grace, Carrie Coon, Sigourney Weaver",
        plot:
          "When a single mom and her two kids arrive in a small town, they begin to discover their connection to the original Ghostbusters and the secret legacy their grandfather left behind.",
        country: "USA, Canada",
        poster:
          "https://m.media-amazon.com/images/M/MV5BMGZmOGJjYjYtMWFkZi00NTE2LTk5NjktOGZiNDM2ZjBiMjk5XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
      },
      {
        id: 13,
        title: "Wonder Woman 1984",
        year: "2020",
        rated: "PG-13",
        release: "2020.08.14",
        duration: "N/A",
        genre: "Action",
        director: "Patty Jenkins",
        writer: "Geoff Johns, Patty Jenkins",
        actors: "Pedro Pascal, Connie Nielsen, Gal Gadot, Robin Wright",
        plot:
          "Plot unknown. A sequel to the 2017 superhero film 'Wonder Woman.'",
        country: "UK, Mexico, Spain, Canada, USA",
        poster:
          "https://m.media-amazon.com/images/M/MV5BYzAyOGJkMzUtMmRjYS00NGJmLWExNGEtYzI2YjVmMmQzMzFiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
      },
      {
        id: 14,
        title: "Parasite",
        year: "2019",
        rated: "R",
        release: "2019.11.08",
        duration: "132 min",
        genre: "Comedy, Drama, Thriller",
        director: "Bong Joon Ho",
        writer: "Bong Joon Ho, Bong Joon Ho, Jin Won Han",
        actors: "Kang-ho Song, Sun-kyun Lee, Yeo-jeong Jo, Woo-sik Choi",
        plot:
          "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
        country: "South Korea",
        poster:
          "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
      },
      {
        id: 15,
        title: "Us",
        year: "2019",
        rated: "R",
        release: "2019.03.22",
        duration: "116 min",
        genre: "Horror, Thriller",
        director: "Jordan Peele",
        writer: "Jordan Peele",
        actors: "Lupita Nyong'o, Winston Duke, Elisabeth Moss, Tim Heidecker",
        plot:
          "A family's serene beach vacation turns to chaos when their doppelgängers appear and begin to terrorize them.",
        country: "USA, China, Japan",
        poster:
          "https://m.media-amazon.com/images/M/MV5BZTliNWJhM2YtNDc1MC00YTk1LWE2MGYtZmE4M2Y5ODdlNzQzXkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_SX300.jpg",
      },
      {
        id: 16,
        title: "Knives Out",
        year: "2019",
        rated: "PG-13",
        release: "2019.11.27",
        duration: "131 min",
        genre: "Comedy, Drama, Thriller",
        director: "Rian Johnson",
        writer: "Rian Johnson",
        actors: "Daniel Craig, Chris Evans, Ana de Armas, Jamie Lee Curtis",
        plot:
          "A detective investigates the death of a patriarch of an eccentric, combative family.",
        country: "USA",
        poster:
          "https://m.media-amazon.com/images/M/MV5BMGUwZjliMTAtNzAxZi00MWNiLWE2NzgtZGUxMGQxZjhhNDRiXkEyXkFqcGdeQXVyNjU1NzU3MzE@._V1_SX300.jpg",
      },
      {
        id: 17,
        title: "Toy Story 4",
        year: "2019",
        rated: "G",
        release: "2019.06.21",
        duration: "100 min",
        genre: "Animation, Comedy, Family",
        director: "Josh Cooley",
        writer: "John Lasseter, Andrew Stanton, Josh Cooley, Valerie LaPointe",
        actors: "Tom Hanks, Tim Allen, Annie Potts, Tony Hale",
        plot:
          'When a new toy called "Forky" joins Woody and the gang, a road trip alongside old and new friends reveals how big the world can be for a toy.',
        country: "USA",
        poster:
          "https://m.media-amazon.com/images/M/MV5BMTYzMDM4NzkxOV5BMl5BanBnXkFtZTgwNzM1Mzg2NzM@._V1_SX300.jpg",
      },
      {
        id: 18,
        title: "Little Women",
        year: "2019",
        rated: "PG",
        release: "2019.12.25",
        duration: "135 min",
        genre: "Drama, Romance",
        director: "Greta Gerwig",
        writer: "Greta Gerwig, Louisa May Alcott",
        actors: "Saoirse Ronan, Emma Watson, Florence Pugh, Eliza Scanlen",
        plot:
          "Jo March reflects back and forth on her life, telling the beloved story of the March sisters - four young women, each determined to live life on her own terms.",
        country: "USA",
        poster:
          "https://m.media-amazon.com/images/M/MV5BY2QzYTQyYzItMzAwYi00YjZlLThjNTUtNzMyMDdkYzJiNWM4XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
      },
      {
        id: 19,
        title: "Booksmart",
        year: "2019",
        rated: "R",
        release: "2019.05.24",
        duration: "102 min",
        genre: "Comedy",
        director: "Olivia Wilde",
        writer: "Emily Halpern, Sarah Haskins, Susanna Fogel, Katie Silberman",
        actors:
          "Kaitlyn Dever, Beanie Feldstein, Jessica Williams, Jason Sudeikis",
        plot:
          "On the eve of their high school graduation, two academic superstars and best friends realize they should have worked less and played more. Determined not to fall short of their peers, the girls try to cram four years of fun into one night.",
        country: "USA",
        poster:
          "https://m.media-amazon.com/images/M/MV5BMjEzMjcxNjA2Nl5BMl5BanBnXkFtZTgwMjAxMDM2NzM@._V1_SX300.jpg",
      },
      {
        id: 20,
        title: "The Farewell",
        year: "2019",
        rated: "PG",
        release: "2019.08.09",
        duration: "100 min",
        genre: "Comedy, Drama",
        director: "Lulu Wang",
        writer: "Lulu Wang",
        actors: "Shuzhen Zhao, Awkwafina, X Mayo, Hong Lu",
        plot:
          "A Chinese family discovers their grandmother has only a short while left to live and decide to keep her in the dark, scheduling a wedding to gather before she dies.",
        country: "USA",
        poster:
          "https://m.media-amazon.com/images/M/MV5BMWE3MjViNWUtY2VjYS00ZDBjLTllMzYtN2FkY2QwYmRiMDhjXkEyXkFqcGdeQXVyODQzNTE3ODc@._V1_SX300.jpg",
      },
      {
        id: 21,
        title: "Once Upon a Time... in Hollywood",
        year: "2019",
        rated: "R",
        release: "2019.07.26",
        duration: "161 min",
        genre: "Comedy, Drama",
        director: "Quentin Tarantino",
        writer: "Quentin Tarantino",
        actors: "Leonardo DiCaprio, Brad Pitt, Margot Robbie, Emile Hirsch",
        plot:
          "A faded television actor and his stunt double strive to achieve fame and success in the film industry during the final years of Hollywood's Golden Age in 1969 Los Angeles.",
        country: "USA, UK, China",
        poster:
          "https://m.media-amazon.com/images/M/MV5BOTg4ZTNkZmUtMzNlZi00YmFjLTk1MmUtNWQwNTM0YjcyNTNkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_SX300.jpg",
      },
      {
        id: 22,
        title: "Ford v Ferrari",
        year: "2019",
        rated: "PG-13",
        release: "2019.11.15",
        duration: "152 min",
        genre: "Action, Drama",
        director: "James Mangold",
        writer: "Jez Butterworth, John-Henry Butterworth, Jason Keller",
        actors: "Matt Damon, Christian Bale, Jon Bernthal, Caitriona Balfe",
        plot:
          "American car designer Carroll Shelby and driver Ken Miles battle corporate interference and the laws of physics to build a revolutionary race car for Ford in order to defeat Ferrari at the 24 Hours of Le Mans in 1966.",
        country: "USA, France",
        poster:
          "https://m.media-amazon.com/images/M/MV5BM2UwMDVmMDItM2I2Yi00NGZmLTk4ZTUtY2JjNTQ3OGQ5ZjM2XkEyXkFqcGdeQXVyMTA1OTYzOTUx._V1_SX300.jpg",
      },
      {
        id: 23,
        title: "Honey Boy",
        year: "2019",
        rated: "R",
        release: "2019.11.27",
        duration: "94 min",
        genre: "Drama",
        director: "Alma Har'el",
        writer: "Shia LaBeouf",
        actors: "Shia LaBeouf, Lucas Hedges, Noah Jupe, Byron Bowers",
        plot:
          "A young actor's stormy childhood and early adult years as he struggles to reconcile with his father and deal with his mental health.",
        country: "USA",
        poster:
          "https://m.media-amazon.com/images/M/MV5BZWQ5YThjZjAtNWM3ZC00MDJjLWIzNDktY2Y2Y2FmMTFiNWJmXkEyXkFqcGdeQXVyMTA2MDQ3MTQ3._V1_SX300.jpg",
      },
      {
        id: 24,
        title: "The Lego Movie 2: The Second Part",
        year: "2019",
        rated: "PG",
        release: "2019.02.08",
        duration: "107 min",
        genre: "Animation, Action, Comedy, Family",
        director: "Mike Mitchell",
        writer:
          "Phil Lord , Christopher Miller, Phil Lord , Christopher Miller , Matthew Fogel",
        actors: "Chris Pratt, Elizabeth Banks, Will Arnett, Tiffany Haddish",
        plot:
          "It's been five years since everything was awesome and the citizens are facing a huge new threat: Lego Duplo invaders from outer space, wrecking everything faster than they can rebuild.",
        country: "Denmark, Norway, Australia, USA",
        poster:
          "https://m.media-amazon.com/images/M/MV5BMTkyOTkwNDc1N15BMl5BanBnXkFtZTgwNzkyMzk3NjM@._V1_SX300.jpg",
      },
      {
        id: 25,
        title: "Jojo Rabbit",
        year: "2019",
        rated: "PG-13",
        release: "2019.11.08",
        duration: "108 min",
        genre: "Comedy, Drama",
        director: "Taika Waititi",
        writer: "Taika Waititi, Christine Leunens",
        actors:
          "Roman Griffin Davis, Thomasin McKenzie, Scarlett Johansson, Taika Waititi",
        plot:
          "A young boy in Hitler's army finds out his mother is hiding a Jewish girl in their home.",
        country: "New Zealand, Czech Republic, USA",
        poster:
          "https://m.media-amazon.com/images/M/MV5BZjU0Yzk2MzEtMjAzYy00MzY0LTg2YmItM2RkNzdkY2ZhN2JkXkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_SX300.jpg",
      },
      {
        id: 26,
        title: "Shazam!",
        year: "2019",
        rated: "PG-13",
        release: "2019.04.05",
        duration: "132 min",
        genre: "Action, Comedy",
        director: "David F. Sandberg",
        writer:
          "Henry Gayden, Henry Gayden, Darren Lemke , Bill Parker, C.C. Beck",
        actors: "Zachary Levi, Mark Strong, Asher Angel, Jack Dylan Grazer",
        plot:
          "A newly fostered young boy in search of his mother instead finds unexpected super powers and soon gains a powerful enemy.",
        country: "USA, Canada",
        poster:
          "https://m.media-amazon.com/images/M/MV5BYTE0Yjc1NzUtMjFjMC00Y2I3LTg3NGYtNGRlMGJhYThjMTJmXkEyXkFqcGdeQXVyNTI4MzE4MDU@._V1_SX300.jpg",
      },
      {
        id: 27,
        title: "How to Train Your Dragon: The Hidden World",
        year: "2019",
        rated: "PG",
        release: "2019.02.22",
        duration: "104 min",
        genre: "Animation, Action, Family",
        director: "Dean DeBlois",
        writer: "Dean DeBlois, Cressida Cowell",
        actors:
          "Jay Baruchel, America Ferrera, F. Murray Abraham, Cate Blanchett",
        plot:
          'When Hiccup discovers Toothless isn\'t the only Night Fury, he must seek "The Hidden World", a secret Dragon Utopia before a hired tyrant named Grimmel finds it first.',
        country: "USA, Japan",
        poster:
          "https://m.media-amazon.com/images/M/MV5BMjIwMDIwNjAyOF5BMl5BanBnXkFtZTgwNDE1MDc2NTM@._V1_SX300.jpg",
      },
    ],
  });
});

test("should fetch calendar for a given month from the DB", () => {
  expect(
    reducer(
      { calendar: [] },
      {
        type: "GET_CALENDAR",
        payload: {
          month: 5,
          year: 2020,
        },
      }
    )
  ).toEqual({
    calendar: [
      {
        day: 1,
        month: 5,
        year: 2020,
        date: "2020.5.1",
        timeSlots: [
          {
            time: "18:00",
            filmID: 15,
            seatsAvailable: [65, 77, 99, 64, 59, 83, 41],
          },
          {
            time: "21:00",
            filmID: 24,
            seatsAvailable: [
              16,
              14,
              76,
              93,
              66,
              58,
              88,
              97,
              45,
              93,
              80,
              81,
              89,
              81,
              24,
              64,
              28,
              80,
              65,
              36,
              69,
              18,
              46,
              43,
              53,
              66,
              24,
              99,
              64,
              20,
            ],
          },
        ],
      },
      {
        day: 2,
        month: 5,
        year: 2020,
        date: "2020.5.2",
        timeSlots: [
          {
            time: "15:00",
            filmID: 20,
            seatsAvailable: [
              28,
              99,
              88,
              87,
              74,
              93,
              88,
              97,
              80,
              41,
              82,
              9,
              97,
              86,
              72,
              47,
              57,
              81,
              45,
              95,
              87,
              96,
              10,
              18,
              18,
              68,
              92,
              67,
              14,
              92,
              63,
              69,
              24,
            ],
          },
          {
            time: "18:00",
            filmID: 26,
            seatsAvailable: [
              88,
              81,
              70,
              28,
              57,
              24,
              95,
              12,
              28,
              29,
              3,
              60,
              5,
              1,
              95,
              65,
              86,
              43,
              81,
              12,
              64,
              76,
              30,
              66,
              3,
              14,
              35,
              15,
              75,
              67,
              62,
              62,
              27,
              20,
              73,
              77,
              58,
              51,
              2,
              70,
              51,
              59,
              45,
              53,
              16,
              35,
              52,
              21,
              43,
              43,
              66,
              61,
              16,
              80,
              77,
              50,
              88,
              92,
              54,
              82,
              41,
              66,
              53,
              79,
              19,
              83,
              60,
            ],
          },
          {
            time: "21:00",
            filmID: 22,
            seatsAvailable: [
              35,
              41,
              40,
              43,
              62,
              78,
              85,
              22,
              4,
              50,
              76,
              63,
              29,
              21,
              99,
              20,
              34,
              74,
              21,
              24,
              47,
              29,
              22,
              30,
              52,
            ],
          },
        ],
      },
      {
        day: 3,
        month: 5,
        year: 2020,
        date: "2020.5.3",
        timeSlots: [
          {
            time: "21:00",
            filmID: 20,
            seatsAvailable: [
              24,
              98,
              59,
              51,
              43,
              77,
              57,
              85,
              45,
              43,
              18,
              85,
              47,
              17,
              46,
              1,
              38,
              11,
              84,
              92,
              5,
              64,
              81,
              6,
              49,
              64,
              53,
              11,
              26,
              39,
              73,
              18,
              37,
              7,
              21,
              47,
              55,
              4,
              68,
              4,
              6,
              71,
              80,
              67,
              41,
              68,
              55,
            ],
          },
        ],
      },
      {
        day: 4,
        month: 5,
        year: 2020,
        date: "2020.5.4",
        timeSlots: [
          {
            time: "12:00",
            filmID: 20,
            seatsAvailable: [
              17,
              67,
              29,
              48,
              65,
              42,
              94,
              89,
              49,
              14,
              40,
              28,
              22,
              5,
              25,
              6,
              97,
              15,
              8,
              25,
              0,
              79,
              97,
              46,
              39,
              98,
              0,
              52,
              39,
              57,
              25,
              54,
              86,
              37,
              7,
              66,
              21,
              90,
              98,
              54,
              88,
              22,
              28,
              26,
              4,
              11,
              7,
              13,
              50,
              44,
              87,
              74,
              57,
              62,
              84,
              31,
              67,
              73,
              97,
              6,
              10,
              36,
              59,
              42,
              85,
              77,
              61,
            ],
          },
          {
            time: "15:00",
            filmID: 23,
            seatsAvailable: [
              32,
              64,
              4,
              19,
              85,
              76,
              32,
              94,
              83,
              69,
              52,
              62,
              70,
              84,
              81,
              6,
              9,
              83,
              22,
              20,
              3,
              2,
            ],
          },
          {
            time: "18:00",
            filmID: 22,
            seatsAvailable: [
              23,
              33,
              19,
              99,
              96,
              26,
              89,
              81,
              20,
              98,
              19,
              74,
              89,
              73,
              31,
              66,
              0,
              40,
              24,
              95,
              34,
              24,
              24,
              33,
              24,
              57,
              52,
              33,
              55,
              67,
              70,
              54,
              64,
              70,
            ],
          },
          {
            time: "21:00",
            filmID: 15,
            seatsAvailable: [
              36,
              96,
              6,
              24,
              77,
              43,
              82,
              40,
              58,
              20,
              46,
              32,
              57,
              10,
              33,
              53,
              3,
              74,
              11,
              2,
              4,
              90,
              64,
              52,
              40,
              73,
              86,
              90,
              30,
              87,
              15,
              34,
              21,
              3,
              46,
              16,
              35,
              26,
              70,
              1,
              58,
              84,
              83,
              1,
              79,
              34,
              8,
              72,
              0,
              35,
            ],
          },
        ],
      },
      {
        day: 5,
        month: 5,
        year: 2020,
        date: "2020.5.5",
        timeSlots: [
          {
            time: "18:00",
            filmID: 24,
            seatsAvailable: [
              66,
              26,
              44,
              20,
              43,
              82,
              30,
              18,
              68,
              52,
              94,
              77,
              3,
              83,
              28,
              24,
              94,
              57,
              34,
              60,
              3,
              71,
              41,
              59,
              53,
              67,
              51,
              43,
              11,
              74,
              80,
              19,
              37,
              84,
              78,
              4,
              82,
              78,
              78,
              13,
              13,
              43,
              51,
              55,
              99,
              82,
              2,
            ],
          },
          {
            time: "21:00",
            filmID: 20,
            seatsAvailable: [
              95,
              29,
              12,
              15,
              52,
              7,
              11,
              45,
              92,
              89,
              16,
              79,
              10,
              97,
              52,
              97,
              28,
              41,
              8,
              44,
              9,
              89,
              56,
              13,
              96,
              61,
              62,
              1,
              18,
              2,
              21,
              39,
              37,
              17,
              72,
              48,
              43,
              98,
              10,
              33,
              25,
              25,
              88,
              33,
              13,
              34,
              47,
              1,
              73,
              84,
              64,
              50,
              57,
              11,
              26,
              75,
              72,
              92,
              32,
              28,
              3,
              85,
              8,
              93,
              10,
              72,
            ],
          },
        ],
      },
      {
        day: 6,
        month: 5,
        year: 2020,
        date: "2020.5.6",
        timeSlots: [
          {
            time: "18:00",
            filmID: 18,
            seatsAvailable: [
              37,
              24,
              35,
              50,
              85,
              16,
              6,
              46,
              39,
              36,
              54,
              75,
              38,
              9,
              7,
              34,
              95,
              33,
              34,
              58,
              49,
              60,
              82,
              9,
              19,
              71,
              93,
              77,
              96,
              21,
              68,
              59,
              49,
              33,
              57,
              74,
              74,
              53,
              81,
              42,
              40,
              27,
            ],
          },
          {
            time: "21:00",
            filmID: 15,
            seatsAvailable: [
              82,
              29,
              34,
              41,
              2,
              56,
              43,
              0,
              14,
              64,
              22,
              75,
              43,
              31,
              89,
              49,
              88,
              9,
              22,
              94,
              9,
              4,
              46,
              71,
              54,
              94,
              57,
              42,
              19,
              50,
              7,
              14,
              19,
              9,
              32,
              51,
              53,
              86,
              91,
              26,
              84,
              41,
              93,
              29,
              73,
              40,
              21,
              83,
              80,
              10,
              63,
              94,
              29,
              76,
              4,
              49,
              15,
              4,
              77,
              2,
              55,
              59,
              85,
              22,
              24,
              80,
              34,
            ],
          },
        ],
      },
      {
        day: 7,
        month: 5,
        year: 2020,
        date: "2020.5.7",
        timeSlots: [
          {
            time: "21:00",
            filmID: 26,
            seatsAvailable: [29, 76, 61, 4, 91, 34],
          },
        ],
      },
      {
        day: 8,
        month: 5,
        year: 2020,
        date: "2020.5.8",
        timeSlots: [
          {
            time: "15:00",
            filmID: 17,
            seatsAvailable: [14, 40, 28],
          },
          {
            time: "18:00",
            filmID: 23,
            seatsAvailable: [
              73,
              81,
              53,
              75,
              71,
              41,
              37,
              12,
              28,
              77,
              43,
              79,
              37,
              50,
              22,
              72,
              26,
              23,
              52,
              21,
              94,
              46,
              10,
              58,
              32,
              75,
              63,
              17,
              60,
              25,
              67,
              47,
              97,
              80,
              51,
              39,
              78,
              40,
              29,
              87,
              1,
              58,
              80,
              49,
              14,
              10,
              35,
              79,
              99,
              40,
              85,
              15,
              84,
              41,
              97,
              32,
              3,
              52,
              8,
              55,
              6,
              17,
              37,
              76,
            ],
          },
          {
            time: "21:00",
            filmID: 19,
            seatsAvailable: [
              50,
              38,
              91,
              65,
              80,
              10,
              15,
              68,
              67,
              38,
              17,
              30,
              74,
              6,
              25,
              88,
              75,
              15,
              95,
              30,
              73,
              67,
              15,
              83,
              27,
              67,
              22,
            ],
          },
        ],
      },
      {
        day: 9,
        month: 5,
        year: 2020,
        date: "2020.5.9",
        timeSlots: [
          {
            time: "12:00",
            filmID: 22,
            seatsAvailable: [
              48,
              94,
              18,
              89,
              68,
              75,
              47,
              81,
              45,
              48,
              25,
              88,
              48,
              90,
              74,
              71,
              68,
              69,
              92,
              48,
              11,
              62,
              41,
              38,
              69,
              44,
              68,
              7,
              72,
              54,
              40,
              11,
              77,
              76,
              76,
              76,
              29,
              62,
              42,
              25,
              74,
              50,
              13,
              30,
              61,
              54,
              27,
              39,
              55,
            ],
          },
          {
            time: "15:00",
            filmID: 27,
            seatsAvailable: [
              92,
              74,
              5,
              43,
              30,
              12,
              16,
              83,
              63,
              22,
              26,
              21,
              26,
              89,
              59,
              82,
              35,
              82,
              57,
              69,
              7,
              69,
              67,
              45,
              73,
              97,
              63,
              5,
              17,
              11,
              11,
              64,
              36,
              53,
              14,
              44,
              85,
              79,
              30,
              30,
              87,
              35,
              98,
              96,
              98,
              12,
              29,
              71,
              14,
              77,
              58,
              13,
              24,
            ],
          },
          {
            time: "18:00",
            filmID: 24,
            seatsAvailable: [
              99,
              9,
              6,
              1,
              91,
              39,
              19,
              38,
              46,
              67,
              64,
              93,
              96,
              24,
              71,
              8,
              81,
              34,
              63,
              50,
              96,
              9,
              37,
              62,
              83,
              81,
              28,
              93,
              83,
              13,
              55,
              89,
              99,
              20,
              1,
              67,
              27,
              52,
              68,
              34,
              31,
              5,
              63,
              53,
              93,
              19,
              22,
              70,
              44,
              38,
              55,
              61,
              57,
              58,
              6,
              80,
              58,
              66,
              88,
              68,
            ],
          },
          {
            time: "21:00",
            filmID: 18,
            seatsAvailable: [53, 97, 71, 86, 66, 12, 24, 21],
          },
        ],
      },
      {
        day: 10,
        month: 5,
        year: 2020,
        date: "2020.5.10",
        timeSlots: [
          {
            time: "21:00",
            filmID: 21,
            seatsAvailable: [
              81,
              21,
              21,
              37,
              29,
              55,
              44,
              51,
              0,
              23,
              68,
              81,
              21,
              45,
            ],
          },
        ],
      },
      {
        day: 11,
        month: 5,
        year: 2020,
        date: "2020.5.11",
        timeSlots: [
          {
            time: "21:00",
            filmID: 15,
            seatsAvailable: [
              64,
              17,
              6,
              97,
              8,
              27,
              7,
              34,
              2,
              10,
              84,
              63,
              41,
              74,
              52,
              21,
              95,
              18,
              2,
              86,
              44,
              26,
              41,
              96,
              40,
            ],
          },
        ],
      },
      {
        day: 12,
        month: 5,
        year: 2020,
        date: "2020.5.12",
        timeSlots: [
          {
            time: "18:00",
            filmID: 15,
            seatsAvailable: [51, 29, 55, 60, 30, 89, 8, 8, 68, 69, 5, 80, 67],
          },
          {
            time: "21:00",
            filmID: 26,
            seatsAvailable: [
              77,
              19,
              86,
              37,
              84,
              25,
              35,
              57,
              21,
              18,
              26,
              80,
              63,
              94,
              24,
              15,
              17,
              33,
              58,
              45,
              67,
              20,
              65,
              22,
              88,
              35,
              31,
              44,
              45,
              92,
              49,
              65,
            ],
          },
        ],
      },
      {
        day: 13,
        month: 5,
        year: 2020,
        date: "2020.5.13",
        timeSlots: [
          {
            time: "12:00",
            filmID: 16,
            seatsAvailable: [
              18,
              47,
              1,
              15,
              72,
              50,
              11,
              7,
              74,
              37,
              49,
              67,
              74,
              96,
              68,
              26,
              1,
            ],
          },
          {
            time: "15:00",
            filmID: 27,
            seatsAvailable: [
              12,
              9,
              69,
              56,
              85,
              92,
              76,
              19,
              22,
              54,
              31,
              19,
              70,
              85,
              42,
              86,
              73,
              25,
              47,
              70,
              98,
              79,
              36,
              95,
            ],
          },
          {
            time: "18:00",
            filmID: 15,
            seatsAvailable: [
              76,
              67,
              3,
              1,
              76,
              23,
              91,
              58,
              4,
              57,
              69,
              87,
              97,
              54,
              89,
              3,
              18,
              42,
              8,
              7,
              35,
            ],
          },
          {
            time: "21:00",
            filmID: 25,
            seatsAvailable: [
              3,
              36,
              95,
              59,
              56,
              69,
              17,
              27,
              88,
              32,
              42,
              94,
              29,
              19,
              65,
              49,
              98,
              9,
              6,
              88,
              53,
              45,
              61,
              28,
              7,
              55,
              22,
              33,
              88,
              8,
              7,
              41,
              54,
              84,
              99,
              18,
              5,
              60,
              66,
              61,
              24,
              93,
              10,
              12,
              19,
              22,
              5,
              48,
              83,
              4,
              44,
              15,
            ],
          },
        ],
      },
      {
        day: 14,
        month: 5,
        year: 2020,
        date: "2020.5.14",
        timeSlots: [
          {
            time: "21:00",
            filmID: 24,
            seatsAvailable: [
              14,
              1,
              26,
              9,
              51,
              20,
              40,
              40,
              14,
              2,
              97,
              17,
              51,
              16,
              67,
              24,
              70,
              61,
              76,
              85,
              87,
              39,
              67,
              34,
              53,
              57,
              1,
              68,
              43,
              74,
              70,
              20,
              22,
              51,
              71,
              83,
            ],
          },
        ],
      },
      {
        day: 15,
        month: 5,
        year: 2020,
        date: "2020.5.15",
        timeSlots: [
          {
            time: "15:00",
            filmID: 15,
            seatsAvailable: [
              87,
              56,
              61,
              22,
              79,
              47,
              37,
              92,
              49,
              17,
              43,
              59,
              48,
              60,
              58,
              98,
              72,
              97,
              32,
              18,
              42,
              82,
              36,
              12,
              31,
              96,
              8,
              9,
              74,
              93,
              44,
              58,
              68,
              61,
              6,
              62,
              58,
              36,
              68,
              37,
              11,
              62,
              61,
              55,
              64,
              17,
              29,
              55,
              71,
              60,
              54,
              71,
              42,
              51,
              12,
              62,
              18,
              52,
              49,
              99,
              14,
              6,
              57,
              14,
              45,
              58,
              9,
            ],
          },
          {
            time: "18:00",
            filmID: 27,
            seatsAvailable: [
              12,
              44,
              61,
              47,
              37,
              53,
              79,
              46,
              8,
              37,
              30,
              66,
              17,
              28,
              81,
              74,
              47,
              26,
              55,
              59,
              18,
              85,
              78,
              85,
              83,
              27,
              44,
              9,
              26,
              51,
              37,
              46,
              25,
              14,
              29,
              5,
              30,
              97,
              96,
              22,
              19,
              50,
              59,
              10,
              72,
              24,
              38,
              64,
              16,
              84,
              18,
              33,
              31,
              75,
              0,
              92,
              95,
              49,
              48,
            ],
          },
          {
            time: "21:00",
            filmID: 14,
            seatsAvailable: [
              83,
              91,
              39,
              34,
              39,
              53,
              29,
              48,
              25,
              42,
              34,
              11,
              81,
              96,
              23,
              60,
              22,
              75,
              55,
              36,
              55,
              72,
              31,
              94,
              9,
              73,
            ],
          },
        ],
      },
      {
        day: 16,
        month: 5,
        year: 2020,
        date: "2020.5.16",
        timeSlots: [
          {
            time: "12:00",
            filmID: 16,
            seatsAvailable: [88, 91, 20, 39, 57, 5, 19],
          },
          {
            time: "15:00",
            filmID: 20,
            seatsAvailable: [
              47,
              50,
              11,
              81,
              56,
              19,
              40,
              85,
              44,
              36,
              95,
              69,
              14,
              88,
              30,
              97,
              8,
              7,
              67,
              11,
              74,
              36,
              55,
              72,
              59,
              80,
              84,
              83,
              86,
              57,
              5,
              67,
              68,
              5,
              64,
              16,
              25,
              97,
              77,
              56,
              66,
              37,
              82,
              75,
              36,
              87,
              45,
              1,
              24,
            ],
          },
          {
            time: "18:00",
            filmID: 20,
            seatsAvailable: [
              76,
              41,
              97,
              34,
              94,
              56,
              27,
              2,
              92,
              34,
              87,
              97,
              48,
              7,
              11,
              0,
              94,
              97,
              12,
              24,
              6,
              49,
              8,
              37,
              85,
              62,
              46,
              95,
              96,
              40,
              32,
              75,
            ],
          },
          {
            time: "21:00",
            filmID: 19,
            seatsAvailable: [
              13,
              31,
              62,
              94,
              88,
              32,
              0,
              37,
              97,
              37,
              49,
              61,
              78,
              0,
              36,
              54,
              69,
              60,
              30,
            ],
          },
        ],
      },
      {
        day: 17,
        month: 5,
        year: 2020,
        date: "2020.5.17",
        timeSlots: [
          {
            time: "21:00",
            filmID: 27,
            seatsAvailable: [
              35,
              72,
              39,
              40,
              47,
              26,
              53,
              62,
              34,
              27,
              34,
              91,
              26,
              70,
              98,
              87,
              86,
              21,
              62,
              32,
              22,
              96,
              22,
              89,
              17,
              70,
              30,
              73,
              35,
              36,
              0,
              5,
              93,
              43,
              37,
              13,
              6,
              78,
              54,
              6,
              2,
              96,
              62,
              31,
              56,
              82,
              23,
              72,
              54,
              36,
              12,
              37,
              78,
              88,
              4,
              41,
              78,
              45,
              67,
              58,
              1,
              79,
              54,
              18,
            ],
          },
        ],
      },
      {
        day: 18,
        month: 5,
        year: 2020,
        date: "2020.5.18",
        timeSlots: [
          {
            time: "12:00",
            filmID: 20,
            seatsAvailable: [
              18,
              31,
              77,
              81,
              24,
              86,
              10,
              85,
              62,
              93,
              56,
              71,
              13,
              57,
              28,
              13,
              67,
              50,
              48,
              4,
              13,
              98,
              95,
              93,
              30,
              46,
              71,
              21,
              16,
              5,
              26,
              41,
              24,
              35,
              19,
              82,
              30,
              41,
              71,
              6,
              24,
              37,
              20,
              84,
            ],
          },
          {
            time: "15:00",
            filmID: 17,
            seatsAvailable: [
              68,
              99,
              47,
              49,
              22,
              12,
              30,
              16,
              35,
              4,
              85,
              21,
              37,
              25,
              15,
              72,
              64,
              95,
              64,
              85,
              51,
              68,
              88,
              93,
              3,
              10,
              7,
              75,
              18,
              91,
              19,
              66,
              71,
              51,
              38,
              51,
              11,
              45,
              69,
              33,
              88,
              8,
              91,
              32,
              69,
              88,
              55,
              0,
              32,
              60,
              86,
            ],
          },
          {
            time: "18:00",
            filmID: 20,
            seatsAvailable: [
              54,
              58,
              48,
              6,
              92,
              49,
              47,
              7,
              91,
              16,
              34,
              41,
              98,
              7,
              80,
              39,
              70,
              9,
              45,
              45,
              0,
              45,
              55,
              81,
              71,
              93,
              20,
              11,
              71,
              92,
              1,
              38,
              80,
              32,
              88,
              24,
              13,
              11,
              81,
              42,
              45,
              37,
              97,
              27,
              84,
              50,
              49,
              64,
              14,
              91,
              59,
              24,
              56,
              59,
              6,
              85,
              69,
              58,
              3,
              88,
              25,
              0,
            ],
          },
          {
            time: "21:00",
            filmID: 16,
            seatsAvailable: [
              68,
              77,
              13,
              71,
              32,
              17,
              99,
              64,
              23,
              70,
              78,
              21,
              41,
              97,
              1,
              36,
              53,
              56,
              50,
              12,
              16,
              16,
              92,
              88,
              3,
              25,
              13,
              91,
              95,
              97,
              79,
              96,
              0,
              48,
              36,
              17,
              90,
              75,
            ],
          },
        ],
      },
      {
        day: 19,
        month: 5,
        year: 2020,
        date: "2020.5.19",
        timeSlots: [
          {
            time: "21:00",
            filmID: 20,
            seatsAvailable: [
              49,
              37,
              84,
              9,
              17,
              75,
              52,
              3,
              51,
              31,
              14,
              35,
              50,
              51,
              87,
              62,
              1,
              18,
              6,
              62,
              42,
              4,
              0,
              81,
              0,
              31,
              4,
              83,
              29,
              36,
              19,
              16,
              88,
              54,
              56,
              84,
              70,
              74,
            ],
          },
        ],
      },
      {
        day: 20,
        month: 5,
        year: 2020,
        date: "2020.5.20",
        timeSlots: [
          {
            time: "21:00",
            filmID: 23,
            seatsAvailable: [
              29,
              36,
              3,
              78,
              14,
              6,
              53,
              9,
              69,
              65,
              60,
              32,
              43,
              61,
              27,
              43,
              50,
              10,
              64,
              43,
              35,
              84,
              35,
              26,
              92,
              49,
              4,
              93,
              10,
              24,
              7,
              4,
              59,
              60,
            ],
          },
        ],
      },
      {
        day: 21,
        month: 5,
        year: 2020,
        date: "2020.5.21",
        timeSlots: [
          {
            time: "15:00",
            filmID: 18,
            seatsAvailable: [
              47,
              78,
              25,
              91,
              96,
              32,
              26,
              67,
              74,
              95,
              52,
              75,
              16,
              55,
              90,
              72,
              67,
              14,
              37,
              80,
              74,
              61,
            ],
          },
          {
            time: "18:00",
            filmID: 20,
            seatsAvailable: [
              93,
              24,
              29,
              80,
              9,
              13,
              50,
              4,
              52,
              25,
              99,
              98,
              9,
              3,
              32,
              89,
              77,
              36,
              18,
              68,
              25,
              98,
              77,
              3,
              74,
              32,
              3,
              45,
              54,
              27,
              53,
              76,
              82,
              80,
              44,
              25,
              25,
              99,
              33,
              88,
              47,
              18,
              60,
              46,
              47,
              50,
              44,
            ],
          },
          {
            time: "21:00",
            filmID: 26,
            seatsAvailable: [
              57,
              60,
              38,
              13,
              94,
              38,
              22,
              44,
              30,
              63,
              74,
              67,
              98,
              11,
              6,
              17,
              56,
              39,
              2,
              88,
              61,
              15,
              90,
              92,
            ],
          },
        ],
      },
      {
        day: 22,
        month: 5,
        year: 2020,
        date: "2020.5.22",
        timeSlots: [
          {
            time: "15:00",
            filmID: 18,
            seatsAvailable: [],
          },
          {
            time: "18:00",
            filmID: 27,
            seatsAvailable: [
              85,
              24,
              44,
              9,
              88,
              0,
              82,
              99,
              94,
              85,
              44,
              99,
              63,
              24,
              82,
              57,
              79,
              1,
              36,
              84,
              61,
              75,
              59,
              65,
              40,
              96,
              15,
              92,
              16,
              13,
              0,
              11,
              89,
              82,
              70,
              80,
              94,
              62,
              46,
              64,
              9,
              25,
            ],
          },
          {
            time: "21:00",
            filmID: 19,
            seatsAvailable: [
              63,
              3,
              2,
              40,
              94,
              59,
              71,
              36,
              74,
              92,
              7,
              25,
              72,
              67,
              56,
              5,
              0,
              37,
              97,
              17,
              49,
              4,
              46,
              59,
              80,
              90,
              60,
              2,
              93,
              67,
              42,
              50,
              6,
              44,
              64,
              86,
              37,
              30,
              81,
              94,
              54,
              43,
              8,
              59,
              82,
              92,
              29,
              70,
              11,
              3,
              79,
              10,
              66,
              99,
              77,
              15,
              13,
              51,
              95,
              72,
              1,
              98,
              94,
              43,
              18,
              57,
              91,
              49,
            ],
          },
        ],
      },
      {
        day: 23,
        month: 5,
        year: 2020,
        date: "2020.5.23",
        timeSlots: [
          {
            time: "21:00",
            filmID: 22,
            seatsAvailable: [
              8,
              81,
              59,
              79,
              88,
              76,
              29,
              51,
              99,
              73,
              27,
              89,
              45,
              30,
              86,
              16,
              22,
              47,
              74,
              18,
              98,
              30,
              66,
              73,
              70,
              72,
              31,
              48,
              27,
              27,
              86,
              51,
              61,
              85,
              96,
              3,
            ],
          },
        ],
      },
      {
        day: 24,
        month: 5,
        year: 2020,
        date: "2020.5.24",
        timeSlots: [
          {
            time: "15:00",
            filmID: 23,
            seatsAvailable: [
              96,
              92,
              13,
              10,
              8,
              74,
              66,
              51,
              88,
              38,
              63,
              36,
              1,
              85,
              32,
              73,
              46,
              29,
            ],
          },
          {
            time: "18:00",
            filmID: 24,
            seatsAvailable: [
              67,
              22,
              68,
              66,
              3,
              73,
              63,
              13,
              8,
              62,
              94,
              0,
              93,
              24,
              65,
              91,
              66,
              94,
              41,
              29,
              84,
              37,
              58,
              54,
              95,
              61,
              79,
              4,
              30,
              81,
              66,
              46,
              51,
              37,
              42,
              0,
              88,
              81,
              90,
              46,
              72,
            ],
          },
          {
            time: "21:00",
            filmID: 23,
            seatsAvailable: [
              69,
              77,
              37,
              89,
              66,
              65,
              48,
              8,
              87,
              86,
              84,
              83,
              19,
              76,
              25,
              93,
              37,
              79,
              95,
              88,
              79,
              54,
              53,
              72,
              66,
              92,
              95,
              44,
              64,
              15,
              1,
              49,
              19,
              15,
              3,
              80,
              92,
              45,
              1,
              87,
              42,
              24,
              27,
              13,
              52,
              16,
            ],
          },
        ],
      },
      {
        day: 25,
        month: 5,
        year: 2020,
        date: "2020.5.25",
        timeSlots: [
          {
            time: "12:00",
            filmID: 23,
            seatsAvailable: [
              38,
              17,
              20,
              4,
              39,
              40,
              43,
              31,
              6,
              52,
              64,
              7,
              83,
              76,
              28,
              62,
              24,
              22,
              35,
              67,
              91,
              85,
              38,
              10,
              53,
              27,
              18,
              66,
            ],
          },
          {
            time: "15:00",
            filmID: 25,
            seatsAvailable: [
              94,
              79,
              48,
              28,
              81,
              3,
              37,
              41,
              53,
              33,
              58,
              64,
              87,
              38,
              46,
              82,
              97,
              43,
              0,
              65,
              21,
              37,
              61,
              23,
              34,
              78,
              9,
              12,
              26,
              45,
              55,
              34,
              75,
              95,
              17,
              10,
              20,
              28,
              58,
              80,
              1,
              45,
              80,
              75,
              48,
              69,
              21,
              82,
              56,
              4,
              70,
              55,
              4,
              89,
              4,
              11,
              90,
              61,
              61,
              19,
            ],
          },
          {
            time: "18:00",
            filmID: 23,
            seatsAvailable: [50, 66, 17, 4, 34, 89, 84],
          },
          {
            time: "21:00",
            filmID: 20,
            seatsAvailable: [
              29,
              44,
              17,
              37,
              65,
              64,
              93,
              95,
              9,
              83,
              83,
              52,
              14,
              58,
              79,
              59,
              49,
              80,
              3,
              37,
              4,
              77,
              17,
              65,
              63,
              5,
              66,
              61,
              66,
              80,
              43,
              75,
              45,
              58,
              66,
              65,
              3,
              90,
              66,
              86,
              20,
              41,
              21,
              3,
              30,
              32,
              87,
              40,
              63,
              8,
              86,
              0,
              91,
            ],
          },
        ],
      },
      {
        day: 26,
        month: 5,
        year: 2020,
        date: "2020.5.26",
        timeSlots: [
          {
            time: "15:00",
            filmID: 14,
            seatsAvailable: [
              54,
              70,
              54,
              21,
              82,
              87,
              90,
              5,
              87,
              81,
              78,
              51,
              98,
              62,
              72,
              89,
              20,
              56,
              10,
              82,
              29,
              64,
              6,
              25,
              2,
              63,
              77,
              12,
              93,
              7,
              85,
              61,
              29,
            ],
          },
          {
            time: "18:00",
            filmID: 15,
            seatsAvailable: [
              54,
              53,
              18,
              19,
              37,
              77,
              51,
              47,
              1,
              33,
              77,
              97,
              12,
              92,
              26,
              43,
              86,
              13,
              62,
              5,
              52,
              58,
              66,
              66,
              13,
              52,
              31,
              24,
              67,
              79,
              23,
              13,
              89,
              0,
              23,
              82,
              96,
              98,
              57,
              99,
              87,
              26,
              74,
              69,
              50,
              14,
              47,
              32,
              6,
              38,
              68,
            ],
          },
          {
            time: "21:00",
            filmID: 25,
            seatsAvailable: [
              50,
              29,
              54,
              78,
              82,
              31,
              53,
              85,
              31,
              95,
              29,
              19,
              57,
              95,
            ],
          },
        ],
      },
      {
        day: 27,
        month: 5,
        year: 2020,
        date: "2020.5.27",
        timeSlots: [
          {
            time: "12:00",
            filmID: 23,
            seatsAvailable: [
              36,
              84,
              45,
              6,
              87,
              24,
              12,
              57,
              43,
              57,
              1,
              54,
              33,
              99,
              48,
              81,
              25,
              58,
              10,
              62,
              10,
              89,
              85,
              32,
              86,
              74,
              34,
              61,
              90,
              38,
              44,
              36,
              40,
              48,
              55,
              69,
            ],
          },
          {
            time: "15:00",
            filmID: 21,
            seatsAvailable: [
              57,
              61,
              33,
              39,
              92,
              35,
              91,
              20,
              21,
              6,
              42,
              36,
              6,
              33,
              48,
              61,
              8,
              37,
              9,
              17,
              84,
              23,
              19,
              52,
              44,
              39,
              58,
              33,
              97,
              4,
              96,
              60,
              33,
              94,
              6,
              32,
              1,
              33,
              1,
              22,
              33,
            ],
          },
          {
            time: "18:00",
            filmID: 26,
            seatsAvailable: [
              42,
              32,
              83,
              65,
              65,
              28,
              67,
              16,
              75,
              78,
              93,
              1,
              86,
              71,
              53,
              56,
              23,
            ],
          },
          {
            time: "21:00",
            filmID: 18,
            seatsAvailable: [
              91,
              6,
              8,
              84,
              94,
              95,
              96,
              56,
              65,
              75,
              57,
              93,
              74,
              49,
              92,
              1,
              8,
              98,
              92,
              77,
              55,
              37,
              63,
              76,
              18,
              81,
              35,
              64,
              95,
              2,
              16,
              88,
              75,
              6,
              53,
              36,
              78,
              3,
              69,
              54,
              9,
              69,
              45,
              31,
              22,
              16,
              97,
              71,
              89,
              86,
              10,
              64,
              40,
              23,
              65,
            ],
          },
        ],
      },
      {
        day: 28,
        month: 5,
        year: 2020,
        date: "2020.5.28",
        timeSlots: [
          {
            time: "12:00",
            filmID: 22,
            seatsAvailable: [
              51,
              46,
              11,
              26,
              29,
              18,
              19,
              23,
              97,
              51,
              40,
              95,
              52,
              56,
              78,
            ],
          },
          {
            time: "15:00",
            filmID: 19,
            seatsAvailable: [
              83,
              92,
              80,
              4,
              22,
              61,
              94,
              2,
              6,
              51,
              69,
              28,
              15,
              62,
              50,
              30,
              90,
              48,
              48,
              2,
              34,
              31,
              15,
              92,
              48,
              96,
              17,
              54,
              41,
              96,
              42,
              66,
              71,
              27,
              9,
              88,
              41,
              81,
              4,
              63,
              48,
              10,
              50,
            ],
          },
          {
            time: "18:00",
            filmID: 23,
            seatsAvailable: [
              4,
              50,
              17,
              37,
              35,
              5,
              21,
              87,
              95,
              37,
              38,
              89,
              38,
              3,
              87,
              86,
              86,
              2,
              18,
              7,
            ],
          },
          {
            time: "21:00",
            filmID: 27,
            seatsAvailable: [35, 92, 39, 32],
          },
        ],
      },
      {
        day: 29,
        month: 5,
        year: 2020,
        date: "2020.5.29",
        timeSlots: [
          {
            time: "18:00",
            filmID: 1,
            seatsAvailable: [
              84,
              10,
              0,
              55,
              37,
              58,
              43,
              95,
              1,
              47,
              90,
              84,
              88,
              58,
              52,
              90,
              17,
              33,
              23,
              18,
              51,
              40,
              9,
              25,
              43,
              26,
              76,
              38,
              74,
              11,
              51,
              35,
              66,
              87,
              48,
              29,
              70,
              48,
              55,
              80,
              68,
              86,
              55,
              46,
              44,
              65,
              18,
              71,
              6,
              51,
              78,
              77,
              90,
              75,
              9,
              95,
            ],
          },
          {
            time: "21:00",
            filmID: 19,
            seatsAvailable: [
              47,
              76,
              11,
              36,
              51,
              3,
              37,
              65,
              49,
              30,
              73,
              64,
              7,
              20,
              61,
              92,
              23,
              12,
              45,
              15,
              78,
              37,
              2,
              50,
              78,
              38,
              46,
              11,
              73,
              0,
              46,
              29,
              11,
              26,
              71,
              31,
              73,
              17,
              6,
              71,
              48,
              78,
              77,
              91,
              49,
              83,
              39,
              99,
              45,
              98,
              8,
              79,
              79,
              8,
              48,
              54,
              34,
              7,
              41,
              71,
              25,
            ],
          },
        ],
      },
      {
        day: 30,
        month: 5,
        year: 2020,
        date: "2020.5.30",
        timeSlots: [
          {
            time: "12:00",
            filmID: 17,
            seatsAvailable: [
              81,
              20,
              59,
              56,
              66,
              7,
              54,
              8,
              50,
              20,
              26,
              35,
              90,
              98,
              61,
              50,
              45,
              26,
              28,
              20,
              69,
              88,
              23,
              31,
              23,
              19,
              4,
              26,
              43,
              24,
              38,
              97,
              42,
              59,
              20,
              18,
              51,
              15,
              98,
              69,
              81,
              82,
              95,
              2,
              35,
              23,
              67,
              46,
              60,
              81,
              34,
              59,
              76,
              8,
              75,
              42,
              35,
              95,
            ],
          },
          {
            time: "15:00",
            filmID: 25,
            seatsAvailable: [94, 84, 64, 91, 18, 38, 21, 74, 81, 3, 97],
          },
          {
            time: "18:00",
            filmID: 26,
            seatsAvailable: [
              3,
              74,
              54,
              22,
              40,
              60,
              50,
              51,
              45,
              8,
              44,
              80,
              58,
              68,
              36,
              88,
              72,
              87,
              91,
              97,
              19,
            ],
          },
          {
            time: "21:00",
            filmID: 14,
            seatsAvailable: [
              19,
              83,
              91,
              36,
              95,
              60,
              44,
              88,
              73,
              7,
              65,
              85,
              27,
              48,
              9,
              89,
              92,
              70,
            ],
          },
        ],
      },
      {
        day: 31,
        month: 5,
        year: 2020,
        date: "2020.5.31",
        timeSlots: [
          {
            time: "15:00",
            filmID: 15,
            seatsAvailable: [13, 42, 91, 90],
          },
          {
            time: "18:00",
            filmID: 24,
            seatsAvailable: [
              54,
              71,
              24,
              74,
              71,
              61,
              62,
              9,
              17,
              1,
              3,
              97,
              75,
              30,
              5,
              96,
              62,
              45,
              86,
              62,
              42,
            ],
          },
          {
            time: "21:00",
            filmID: 24,
            seatsAvailable: [
              42,
              67,
              74,
              67,
              65,
              70,
              76,
              25,
              34,
              81,
              51,
              27,
              42,
              0,
              39,
              93,
              92,
              54,
              33,
              93,
              55,
              78,
              53,
              60,
              71,
              36,
              69,
              5,
              74,
              53,
              32,
              98,
              16,
              77,
              7,
              90,
              80,
              31,
              36,
              27,
              94,
              53,
              24,
              18,
              18,
              87,
              69,
              58,
              73,
              44,
              42,
            ],
          },
        ],
      },
    ],
  });
});

test("should fetch calendar entry and films for today", () => {
  expect(
    reducer(
      { todayFilms: {} },
      {
        type: "GET_TODAY_MOVIES",
        payload: {
          day: 19,
          month: 5,
          year: 2020,
        },
      }
    )
  ).toEqual({
    todayFilms: {
      day: 19,
      month: 5,
      year: 2020,
      date: "2020.5.19",
      timeSlots: [
        {
          time: "21:00",
          filmID: 20,
          film: {
            id: 20,
            title: "The Farewell",
            year: "2019",
            rated: "PG",
            release: "2019.08.09",
            duration: "100 min",
            genre: "Comedy, Drama",
            director: "Lulu Wang",
            writer: "Lulu Wang",
            actors: "Shuzhen Zhao, Awkwafina, X Mayo, Hong Lu",
            plot:
              "A Chinese family discovers their grandmother has only a short while left to live and decide to keep her in the dark, scheduling a wedding to gather before she dies.",
            country: "USA",
            poster:
              "https://m.media-amazon.com/images/M/MV5BMWE3MjViNWUtY2VjYS00ZDBjLTllMzYtN2FkY2QwYmRiMDhjXkEyXkFqcGdeQXVyODQzNTE3ODc@._V1_SX300.jpg",
          },
          seatsAvailable: [
            49,
            37,
            84,
            9,
            17,
            75,
            52,
            3,
            51,
            31,
            14,
            35,
            50,
            51,
            87,
            62,
            1,
            18,
            6,
            62,
            42,
            4,
            0,
            81,
            0,
            31,
            4,
            83,
            29,
            36,
            19,
            16,
            88,
            54,
            56,
            84,
            70,
            74,
          ],
        },
      ],
    },
  });
});

test("should fetch calendar entry and films for tomorrow", () => {
  expect(
    reducer(
      { tomorrowFilms: {} },
      {
        type: "GET_TOMORROW_MOVIES",
        payload: {
          day: 19,
          month: 5,
          year: 2020,
        },
      }
    )
  ).toEqual({
    tomorrowFilms: {
      day: 19,
      month: 5,
      year: 2020,
      date: "2020.5.19",
      timeSlots: [
        {
          time: "21:00",
          filmID: 20,
          film: {
            id: 20,
            title: "The Farewell",
            year: "2019",
            rated: "PG",
            release: "2019.08.09",
            duration: "100 min",
            genre: "Comedy, Drama",
            director: "Lulu Wang",
            writer: "Lulu Wang",
            actors: "Shuzhen Zhao, Awkwafina, X Mayo, Hong Lu",
            plot:
              "A Chinese family discovers their grandmother has only a short while left to live and decide to keep her in the dark, scheduling a wedding to gather before she dies.",
            country: "USA",
            poster:
              "https://m.media-amazon.com/images/M/MV5BMWE3MjViNWUtY2VjYS00ZDBjLTllMzYtN2FkY2QwYmRiMDhjXkEyXkFqcGdeQXVyODQzNTE3ODc@._V1_SX300.jpg",
          },
          seatsAvailable: [
            49,
            37,
            84,
            9,
            17,
            75,
            52,
            3,
            51,
            31,
            14,
            35,
            50,
            51,
            87,
            62,
            1,
            18,
            6,
            62,
            42,
            4,
            0,
            81,
            0,
            31,
            4,
            83,
            29,
            36,
            19,
            16,
            88,
            54,
            56,
            84,
            70,
            74,
          ],
        },
      ],
    },
  });
});
